# Generated by Django 5.0.6 on 2024-07-15 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=15)),
                ('IsRegistered', models.BooleanField(null=True)),
                ('occurances', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarkdownText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subheading', models.CharField(max_length=250, null=True)),
                ('link_to_paper', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('authors', models.ManyToManyField(related_name='Posts', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.markdowntext')),
                ('keywords', models.ManyToManyField(related_name='Posts', to='api.keywords')),
            ],
        ),
    ]
