# Generated by Django 5.0.6 on 2024-07-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='IsRegistered',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='occurances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='../uploaded_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
