# Generated by Django 5.0.6 on 2024-07-24 00:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_posts_userbookmark_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookmark',
            unique_together={('user', 'post')},
        ),
    ]
