# Generated by Django 5.0.6 on 2024-08-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
