# Generated by Django 5.0.6 on 2024-08-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_posts_as_post1', to='api.post')),
                ('post2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_posts_as_post2', to='api.post')),
            ],
            options={
                'unique_together': {('post1', 'post2')},
            },
        ),
    ]
