services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      gunicorn api.wsgi:application
