services:
  - type: web
    name: django-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python manage.py migrate
      gunicorn api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.settings
